export const defaultFormValues = {
  gender: 'Female',
  senior_citizen: 0,
  partner: 'No',
  dependents: 'No',
  tenure: 12,
  phone_service: 'Yes',
  multiple_lines: 'No',
  internet_service: 'Fiber optic',
  online_security: 'No',
  online_backup: 'No',
  device_protection: 'No',
  tech_support: 'No',
  streaming_tv: 'Yes',
  streaming_movies: 'Yes',
  contract_type: 'Month-to-month',
  paperless_billing: 'Yes',
  payment_method: 'Electronic check',
  monthly_charges: 75.5,
  total_charges: 905.2,
  churn: null,
};
